MODULE SalesOrderService;

REQUIRE ServiceOrder, ServiceWork, SalesOrder;

NAMESPACE Sales;

serviceOrder = DATA Services.Order (OrderLine);
numberServiceOrder 'Мероприятие' (OrderLine ol) = number(serviceOrder(ol));

countOrderLines 'Кол-во участников' (Services.Order so) = GROUP SUM 1 IF serviceOrder(OrderLine ol) = so;

nameOrderLines 'Участники' (Services.Order so) = GROUP CONCAT name(customer(order(OrderLine l))) IF serviceOrder(l) = so, ', ' ORDER l;

CONSTRAINT SETCHANGED(serviceOrder(OrderLine ol)) AND NOT item(serviceOrder(ol)) = item(ol)
    CHECKED BY serviceOrder[OrderLine]
    MESSAGE 'Продукт заявки не совпадает с продуктом мероприятия';

EXTEND FORM order
    PROPERTIES (l) numberServiceOrder
;

in 'Отм' = DATA BOOLEAN (OrderLine, ServiceWork);

FORM serviceOrderOrderLines 'Выбор участника'
    OBJECTS sw = ServiceWork
    
    OBJECTS l = Sales.OrderLine
    PROPERTIES nameCustomer(l) BACKGROUND (RGB(0,255,255) IF in(l, sw)) ON CHANGE {
        in(l, sw) <- NOT in(l, sw);
    }
    FILTERS serviceOrder(l) = serviceOrder(sw)
;

DESIGN serviceOrderOrderLines {
    BOX(l) { caption = '';}
    PROPERTY(nameCustomer(l)) { caption = 'Имя';}
    REMOVE TOOLBARBOX(l);
}

totalDuration 'Участие, часов' (OrderLine ol) = GROUP SUM duration(ServiceWork sw) IF in(ol, sw);

countOrderLines 'Кол-во участников' (ServiceWork sw) = GROUP SUM 1 IF in(OrderLine l, sw);

nameOrderLines 'Участники' (ServiceWork sw) = GROUP CONCAT name(customer(Sales.order(OrderLine l))) IF in(l, sw) AND serviceOrder(l) = serviceOrder(sw), ', ' ORDER l;

EXTEND FORM Services.order
    PROPERTIES nameOrderLines(sw) ON CHANGE { SHOW serviceOrderOrderLines OBJECTS  sw = sw; }
    
    OBJECTS ol = OrderLine
    PROPERTIES nameStatus 'Status' = nameStatus(order(ol)), nameCustomer 'Customer' = nameCustomer(order(ol)), quantity(ol), untaxedAmount(ol), totalDuration(ol)
    FILTERS serviceOrder(ol) = o 
; 

DESIGN Services.order {
    details {
        NEW orderLines FIRST {
            caption = 'Участники';
            MOVE BOX(ol);
        }
    }
}

EXTEND FORM Services.orders 
    PROPERTIES READONLY countOrderLines(o), nameOrderLines(o)
;

EXTEND FORM serviceWorks
    PROPERTIES READONLY countOrderLines(o), nameOrderLines(o) 
;
