MODULE MyCompanyCustom;

REQUIRE
        IndividualCustom, LegalEntityCustom,
//        CRM,
        Lead, LeadLost, LeadPartner, LeadInitial,
        LeadCustomer, LeadCall, LeadEmail, LeadItemCustom,
        LeadSalesOrder, LeadInvoice, LeadKanbanCustom,
        LeadReport, LeadMarketing, MarketingInitial, LeadReportMarketing,
        LeadDesignCustom,
        
        Manufacturing, Project, ItemSalesCustom,
        ServiceOrder, ServiceWork, SalesOrderService, ServiceWorkLoad, ServiceEquipment
;