MODULE MyCompanyCustom;

REQUIRE
        Eval, ProcessMonitor, Backup, Chat, Documentation,
        IndividualCustom, LegalEntityCustom,
        SalesOrderStatusCustom,
//        CRM,
        Lead, LeadLost, LeadPartner, LeadInitial,
        LeadCustomer, LeadCall, LeadEmail, LeadItemCustom,
        LeadKanbanCustom,
        LeadReport, 
        MarketingInitial, LeadReportMarketing,
        LeadMarketing,
        LeadSalesOrder, LeadInvoice, 
        LeadDesignCustom,
        
        ItemSalesCustom, 
        ServiceOrder, ServiceWork, ServiceOrderStatusCustom, ServiceWorkLoad, ServiceEquipment,
        SalesOrderService
;