MODULE ServiceWorkLoad;

REQUIRE ServiceWork;

NAMESPACE Services;

duration 'Duration' (DATE d, Assignee c) =
    GROUP SUM duration(ServiceWork w) IF startDate(w) = d AND assignee(w) = c;

loadItem = DATA LOCAL Item ();
nameItemLoad 'Продукт' () = name(loadItem());

workOrder (DATE d, Assignee c, Item i) =
    GROUP LAST ServiceWork w ORDER w WHERE startDate(w) = d AND assignee(w) = c AND item(serviceOrder(w)) = i;

duration 'Duration' (DATE d, Assignee c, Item i) =
    GROUP SUM duration(ServiceWork w) IF startDate(w) = d AND assignee(w) = c AND item(serviceOrder(w)) = i;

durationLoad (DATE d, Assignee c, Item i) =
    HTML(CONCAT '', '<b>' + durationToChar(duration(d, c, i)) + '</b>',
        '<font size="-2">(' + durationToChar(duration(d, c)) + ')</font>');

backgroundDurationLoad (DATE d) = CASE WHEN d = currentDate() THEN RGB(224,255,224)
    WHEN extractDOWNumber(d) = 0 OR extractDOWNumber(d) = 6 THEN RGB(255,224,224);

backgroundDurationLoad (DATE d, Assignee c, Item i) =
    IF duration(d, c, i) THEN RGB(224,224,255)
    ELSE backgroundDurationLoad(d);

FORM workOrderDateAssignee 'Активности'
    OBJECTS d = DATE PANEL
    OBJECTS c = Assignee PANEL

    OBJECTS w = ServiceWork
    PROPERTIES(w) READONLY numberServiceOrder, nameServiceOperation, startTime, duration,  endDate, endTime
    PROPERTIES(w) NEWSESSION NEW, EDIT, DELETE
    FILTERS startDate(w) = d,
        assignee(w) = c
;

FORM workCenterLoad 'Загруженность персонала'
    OBJECTS dates = INTERVAL[DATE] PANEL NULL
    PROPERTIES dates '' = VALUE(dates)

    PROPERTIES() nameItemLoad

    OBJECTS d = DATE
    FILTERS iterate(d, from(dates), to(dates))

    OBJECTS c = Assignee
    PROPERTIES(c) READONLY name, id
    PROPERTIES duration 'Duration' = IF duration(d, c, loadItem()) THEN
        durationLoad(d, c, loadItem()) ELSE
        HTML(durationToChar(duration(d, c)))
    COLUMNS (d) HEADER extractDay(d) BACKGROUND backgroundDurationLoad(d, c, loadItem())
    ON CHANGE {
            SHOW workOrderDateAssignee OBJECTS d = d, c = c FLOAT;
    }

    EVENTS ON INIT {
        SEEK workCenterLoad.dates = interval(firstDayOfMonth(currentDate()), lastDayOfMonth(currentDate()));
    }

    PROPERTIES prevInterval '<' = { SEEK workCenterLoad.dates = prevMonthInterval(dates); },
        nextInterval '>' = { SEEK workCenterLoad.dates = nextMonthInterval(dates); }
;

DESIGN workCenterLoad {
    OBJECTS {
        NEW header {
            alignment = STRETCH;
            horizontal = TRUE;
            NEW interval {
                horizontal = TRUE;
                MOVE PROPERTY(prevInterval);
                MOVE PROPERTY(dates);
                MOVE PROPERTY(nextInterval);
            }
            MOVE PROPERTY(nameItemLoad());
        }
        MOVE BOX(c) {
            caption = '';
            PROPERTY(duration) {
                charWidth = 4;
            }
        }
    }
}

NAVIGATOR {
    dashboards {
        NEW workCenterLoad;
    }
}

