MODULE ServiceOrder;

REQUIRE Doc, MetaNumerator, Input, DateUtils, FileUtils, Comments,
BomNested, LocationEmployee,
ServiceOrderType, ServicesSettings;

NAMESPACE Services;

CLASS Order 'Service order';

@defineDocStatus(order, 'Service order status');

type 'Type' = DATA OrderType (Order) NONULL;
nameType 'Type' (Order o) = name(type(o)) CHARWIDTH 15;

WHEN LOCAL SET(Order o IS Order) AND NOT CHANGED(type(o)) DO type(o) <- defaultOrderType();

scheduledDateTime 'Start date' = DATA DATETIME (Order) IN id;
scheduledDateTime(Order o) <- currentDateTime() WHEN SET(o IS Order);
@defineDateTimeAggregation(Order, scheduled, '(scheduled)');

@defineNumberType(Order);

numberDate 'Description' (Order o) = number(o) + ' (' + scheduledDateTime(o) + ')' IN id;

item '{Item}' = DATA Item (Order);
nameItem '{Item}' (Order m) = name(item(m));

uom (Order o) = uom(item(o));
nameUom 'UoM' (Order m) = name(uom(m));

responsible = DATA Employee (Order);
nameResponsible 'Responsible' (Order o) = MasterData.name(responsible(o));

responsible(Order o) <- currentUser() IF currentUser() IS Employee WHEN SET(o IS Order);

// bom
//bom 'Bill of Materials' = DATA Bom (ServiceOrder);
//descriptionBom 'Bill of Materials' (ServiceOrder m) = description(bom(m));
//CONSTRAINT bom(ServiceOrder m) AND NOT item(m) = item(bom(m))
//    CHECKED BY bom[ServiceOrder]
//    MESSAGE 'Service order BOM item must be equal to production order item';
//
//WHEN LOCAL CHANGED(item(ServiceOrder o)) AND NOT CHANGED(bom(o)) AND defaultBom(item(o)) DO
//    bom(o) <- defaultBom(item(o));

company = DATA Company (Order);
nameCompany 'Company' (Order m) = name(company(m));
WHEN LOCAL SET(Order o IS Order) AND NOT CHANGED(company(o)) DO company(o) <- defaultCompany();

materialsLocation 'Materials location' = DATA Location (Order);
nameMaterialsLocation 'Materials location' (Order m) = name(materialsLocation(m));
WHEN LOCAL SETCHANGED(type(Order mo)) AND NOT materialsLocation(mo) DO materialsLocation(mo) <- materialsLocation(type(mo));
CONSTRAINT SETCHANGED(materialsLocation(Order o)) AND internalUse(materialsLocation(o)) CHECKED BY materialsLocation[Order]
    MESSAGE 'The selected location is for internal use';

//unbuild 'Unbuild' (ServiceOrder mo)= unbuild(type(mo));

note 'Note' = DATA ISTRING (Order) CHARWIDTH 20;

// consumed
CLASS ConsumedLine 'Materials';

order = DATA Order (ConsumedLine) NONULL DELETE;

countConsumedLine 'Material lines' (Order m) = GROUP SUM 1 IF order(ConsumedLine l) = m MATERIALIZED;
index '№' = PARTITION SUM 1 ORDER ConsumedLine l BY order(l) IN id MATERIALIZED CHARWIDTH 3;

item '{Item}' = DATA Item (ConsumedLine);
nameItem '{Item}' (ConsumedLine l) = name(item(l));
idBarCodeItem 'Barcode' (ConsumedLine l) = idBarCode(item(l));
idItem '{ID}' (ConsumedLine l) = id(item(l));

description 'Description' = DATA ISTRING (ConsumedLine);

uom (ConsumedLine l) = uom(item(l));
nameUom 'UoM' (ConsumedLine l) = name(uom(l));

toConsume 'To consume' = DATA NUMERIC[16,3] (ConsumedLine);

toConsume 'To consume' (Order o) = GROUP SUM toConsume(ConsumedLine l) IF order(l) = o AND item(l) = item(o) MATERIALIZED;

//// finished
//CLASS FinishedLine 'Finished products';
//
//serviceOrder = DATA ServiceOrder (FinishedLine) NONULL DELETE;
//
//countFinishedLine 'Product lines' (ServiceOrder m) = GROUP SUM 1 IF serviceOrder(ConsumedLine l) = m MATERIALIZED;
//index '№' = PARTITION SUM 1 ORDER FinishedLine l BY serviceOrder(l) IN id MATERIALIZED CHARWIDTH 3;
//
//item '{Item}' = DATA Item (FinishedLine);
//nameItem '{Item}' (FinishedLine l) = name(item(l));
//idBarCodeItem 'Barcode' (FinishedLine l) = idBarCode(item(l));
//idItem '{ID}' (FinishedLine l) = id(item(l));
//
//nameConsumedItem 'Materials' (ServiceOrder o) =
//    GROUP CONCAT nameItem(ConsumedLine cl), ' / ' ORDER nameItem(cl) BY serviceOrder(cl) CHARWIDTH 14;
//
//uom 'UoM' = DATA Uom (FinishedLine);
//nameUom 'UoM' (FinishedLine l) = name(uom(l));
//WHEN LOCAL CHANGED(item(FinishedLine l)) DO uom(l) <- uom(item(l));
//
//toProduce '{Manufacture}' = DATA NUMERIC[16,3] (FinishedLine);
//
//costRatio 'Cost ratio' = DATA NUMERIC[18,5] (FinishedLine);
//
//costRatio (ServiceOrder o) = GROUP SUM costRatio(FinishedLine l) IF serviceOrder(l) = o MATERIALIZED;
//normalizedCostRatio (FinishedLine l) = IF costRatio(serviceOrder(l)) THEN
//    costRatio(l) / costRatio(serviceOrder(l)) ELSE
//    (1.0 IF item(l) = item(serviceOrder(l)));
//
//toProduce '{Manufacture}' (ServiceOrder o) = GROUP SUM toProduce(FinishedLine l) IF serviceOrder(l) = o AND item(l) = item(o) MATERIALIZED;

// line properties
status (ConsumedLine l) = status(order(l));
nameStatus 'Status' (ConsumedLine l) = name(status(l));

nameType 'Type' (ConsumedLine l) = nameType(order(l));
scheduledDateTime 'Start date' (ConsumedLine l) = scheduledDateTime(order(l)) IN id;
scheduledDate 'Start date' (ConsumedLine l) = scheduledDate(order(l));
number 'Number' (ConsumedLine l) = number(order(l)) IN id;

responsible (ConsumedLine l) = responsible(order(l));
nameResponsible 'Responsible' (ConsumedLine l) = MasterData.name(responsible(l));

FORM order 'Мероприятие'
    OBJECTS o = Order PANEL
    PROPERTIES(o) READONLYIF readonly(o)
    nameType, scheduledDateTime, number, nameCompany, nameResponsible,
        nameItem, 
        nameMaterialsLocation,
        note

    OBJECTS c = ConsumedLine
    PROPERTIES(c) READONLYIF readonly(o)
    index READONLY, nameItem, description, nameUom, idBarCodeItem, idItem, toConsume, NEW, DELETE
    FILTERS order(c) = o

    EDIT Order OBJECT o
;

DESIGN order {
    caption = badged('Мероприятие', number(o) + '(' + scheduledDateTime(o) + ')');
    OBJECTS {
        NEW header {
            alignment = STRETCH;
            horizontal = TRUE;
            NEW headerLeft {
                lines = 3;
                MOVE PROPERTY(nameType(o)) { notNull = TRUE; };
                MOVE PROPERTY(nameItem(o));
                MOVE PROPERTY(scheduledDateTime(o));
                MOVE PROPERTY(number(o)) { notNull = TRUE; }
                MOVE PROPERTY(nameCompany(o));
                MOVE PROPERTY(nameResponsible(o));
            }
//            NEW headerRight {
//                fill = 1;
//            }
//            NEW relatedDoc {
//                fill = 1;
//                tabbed = TRUE;
//            }
        }
        MOVE PROPERTY(note(o));
        NEW works {
            fill = 1;
        }
        NEW details {
            fill = 1;
            tabbed = TRUE;
            NEW consumed {
                caption = 'Materials';
                MOVE PROPERTY(nameMaterialsLocation(o));
                NEW consumedPane {
                    horizontal = TRUE;
                    fill = 1;
                    MOVE BOX(c) { caption = ''; }
                    NEW consumedLinesTab {
                        fill = 0.3;
                        tabbed = TRUE;
                    }
                }
            }
        }
    }
    TOOLBARBOX {
        NEW footer FIRST {
            horizontal = TRUE;
        }
    }
}

//edit (FinishedLine l) + { edit(serviceOrder(l)); }
edit (ConsumedLine l) + { edit(order(l)); }

@defineDocHistoryHeader(order, scheduledDateTime);
@defineHistoryProperty(order, item, 'Item', nameItem);
@defineHistoryProperty(order, company, 'Company', nameCompany);
@defineHistoryProperty(order, responsible, 'Responsible', nameResponsible);

//@defineHistoryProperty(serviceOrder, toManufacture, '{Manufacture}'){
//    @defineHistoryProperty(serviceOrder, toManufacture, '{Manufacture}', toManufacture){
//    WHEN CHANGED(toManufacture(ServiceOrder let)) AND NOT DROPPED(let IS ServiceOrder) AND NOT disableHistory() DO {
//        NEW l = ServiceOrderHistory {
//            serviceOrder(l) <- let;
//            dateTime(l) <- currentDateTime();
//            user(l) <- currentUser();
//            computer(l) <- currentComputer();
//            type(l) <- '{Manufacture}';
//            description (l) <- CONCAT ' -> ', PREV(toManufacture(let)), (OVERRIDE ISTRING(toManufacture(let)), '');
//        }
//    }
//};
//};

@defineDocHistoryLine(order, ConsumedLine, item);
@defineDocHistoryLineProperty(order, ConsumedLine, toConsume, 'To consume', nameItem);

background = ABSTRACT CASE COLOR (Order);

FORM orders 'Мероприятия'
    OBJECTS o = Order BACKGROUND background(o)
    PROPERTIES(o) READONLYIF isReadonly()
    number, scheduledDateTime, nameItem, 
    nameType, nameResponsible
//        toManufacture READONLY, 
//        nameUom READONLY,
//        nameMaterialsLocation,
//        countConsumedLine READONLY, 
//        countFinishedLine READONLY
    PROPERTIES(o) NEWSESSION NEW, EDIT, DELETE DISABLEIF readonly(o)

    LIST Order OBJECT o
;

@extendFormEditable(orders);

@defineDocObjectsForm(orders, o, 'План мероприятий');
@defineDocStatusForm(order, o);

WHEN LOCAL SET(Order o IS Order) AND NOT CHANGED(materialsLocation(o)) AND countLocation() = 1 DO
    materialsLocation(o) <- firstLocation();

@defineHistoryForm(order, order, o);

@defineObjectComments(order, o, details);

@defineObjectFiles(order, o, 'Service order file');

NAVIGATOR {
    operations {
        NEW orders;
    }
}

// copy
clone ABSTRACT LIST (Order, Order);

clone(Order to, Order from) + {
    type(to) <- type(from);

    item(to) <- item(from);
    company(to) <- company(from);
    materialsLocation(to) <- materialsLocation(from);

//    FOR serviceOrder(ConsumedLine ml) = from NEW ol = ConsumedLine DO {
//        serviceOrder(ol) <- to;
//        item(ol) <- item(ml);
//        toConsume(ol) <- toConsume(ml);
//    }

//    FOR serviceOrder(FinishedLine ml) = from NEW ol = FinishedLine DO {
//        serviceOrder(ol) <- to;
//        item(ol) <- item(ml);
//        uom(ol) <- uom(ml);
//        toProduce(ol) <- toProduce(ml);
//        costRatio(ol) <- costRatio(ml);
//    }
}

copy 'Copy' (Order from) {
    NEWSESSION {
        NEW to = Order {
            clone(to, from);
            APPLY;
            SHOW order OBJECTS o = to DOCKED;
        }
    }
}

EXTEND FORM order
    PROPERTIES(o) copy
;

DESIGN order {
    secondaryActions {
        MOVE PROPERTY(copy(o)) { valueClass = 'btn-secondary'; }
    }
}

EXTEND FORM orders
    PROPERTIES(o) copy TOOLBAR 
;
