MODULE ServiceWork;

REQUIRE ServiceOrder, ServiceOperation, Doc, Assignee, Time;

NAMESPACE Services;

CLASS ServiceWork 'Work order';

@defineDocStatus(serviceWork, 'Work order status', ready, 'Ready');

name '{Name}' = DATA ISTRING[100] (ServiceWork) CHARWIDTH 20;

serviceOrder 'Service order' = DATA Order (ServiceWork) NONULL DELETE;
countServiceWork (Order o) = GROUP SUM 1 IF serviceOrder(ServiceWork wo) = o;

numberServiceOrder 'Service order' (ServiceWork w) = number(serviceOrder(w));
itemServiceOrder '{Item}' (ServiceWork w) = item(serviceOrder(w));
nameItemServiceOrder '{Item}' (ServiceWork w) = nameItem(serviceOrder(w));

nameNumberServiceOrder (ServiceWork wo) = CONCAT ' ', name(wo), number(serviceOrder(wo));

assignee 'Assignee' = DATA Assignee (ServiceWork) NONULL;
nameAssignee 'Assignee' (ServiceWork w) = name(assignee(w));

assignee(ServiceWork w) <- responsible(serviceOrder(w)) WHEN SET(serviceOrder(w));

//WHEN LOCAL FORMS order SETCHANGED(responsible(Order o)) AND countServiceWork(o) DO {
//    ASK 'Изменить исполнителя в расписании' DO {
//        assignee(ServiceWork sw) <- responsible(o) WHERE serviceOrder(sw) = o;
//    }
//}

in = DATA BOOLEAN (ServiceWork, Assignee);
nameAssignees 'Исполнители' (ServiceWork w) = GROUP CONCAT name(Assignee a) IF in(w, a), ', ' ORDER a;

WHEN LOCAL FORMS order SETCHANGED(responsible(Order o)) AND countServiceWork(o) DO {
    ASK 'Изменить исполнителя в расписании' DO {
        in(ServiceWork sw, Assignee a) <- NULL WHERE serviceOrder(sw) = o;
        in(ServiceWork sw, responsible(o)) <- TRUE WHERE serviceOrder(sw) = o;
    }
}

FORM serviceWorkAssignees 'Выбор исполнителя'
    OBJECTS sw = ServiceWork

    OBJECTS l = Assignee
    PROPERTIES name(l) BACKGROUND (RGB(0,255,255) IF in(sw, l)) ON CHANGE {
        in(sw, l) <- NOT in(sw, l);
    }
//    FILTERS serviceOrder(l) = serviceOrder(sw)
;

DESIGN serviceWorkAssignees {
    BOX(l) { caption = '';}
    PROPERTY(name(l)) { caption = 'Имя';}
    REMOVE TOOLBARBOX(l);
}

lastServiceOperation = DATA LOCAL Operation (Order);

serviceOperation 'Operation' = DATA Operation (ServiceWork) NONULL;
nameServiceOperation 'Operation' (ServiceWork w) = name(serviceOperation(w));

serviceOperation(ServiceWork w) <- lastServiceOperation(serviceOrder(w)) WHEN SET(serviceOrder(w));

//WHEN LOCAL SETCHANGED(serviceOperation(ServiceWork ws)) DO lastServiceOperation(Order o) <- serviceOperation(ws) IF o = serviceOrder(ws);

startDate 'Start date' = DATA DATE (ServiceWork);
startDate(ServiceWork w) <- scheduledDate(serviceOrder(w)) WHEN SET(serviceOrder(w));

lastStartTimeWork = DATA LOCAL TIME(Order);

startTime 'Start time' = DATA TIME (ServiceWork);
startTime(ServiceWork w) <- TIME(scheduledDateTime(serviceOrder(w))) WHEN SET(serviceOrder(w));

//WHEN LOCAL SETCHANGED(startTime(ServiceWork ws)) DO lastStartTimeWork(Order o) <- startTime(ws) IF o = serviceOrder(ws);

endDate 'End date' = DATA DATE (ServiceWork);

endTime 'End time' = DATA TIME (ServiceWork);

lastDurationWork = DATA LOCAL NUMERIC[8,2] (Order);

duration 'Duration' = DATA NUMERIC[8,2] (ServiceWork) CHARWIDTH 5;
durationToChar (NUMERIC[8,2] h) = STRING(rtrim(toChar(h, 'FM99999.99'),'.'));
//duration(ServiceWork w) <- OVERRIDE lastDurationWork(serviceOrder(w)), 1.0 WHEN SET(serviceOrder(w));;

//WHEN LOCAL SETCHANGED(duration(ServiceWork ws)) DO lastDurationWork(Order o) <- duration(ws) IF o = serviceOrder(ws);

prevStartDateTime (ServiceWork sw) = dateTimeToDateTime(PREV(startDate(sw)), PREV(startTime(sw)));

WHEN LOCAL FORMS order SETCHANGED(scheduledDateTime(Order o)) AND countServiceWork(o) DO {
    ASK 'Изменить раcписание' DO {
        LOCAL seconds = INTEGER ();
        seconds() <- subtractSeconds(PREV(scheduledDateTime(o)), scheduledDateTime(o));
        startDate(ServiceWork sw) <- DATE(sumSeconds(prevStartDateTime(sw), seconds())) WHERE serviceOrder(sw) = o;
        startTime(ServiceWork sw) <- TIME(sumSeconds(prevStartDateTime(sw), seconds())) WHERE serviceOrder(sw) = o;
    }
}

WHEN LOCAL FORMS order (SETCHANGED(duration(ServiceWork sw)) OR SETCHANGED(startDate(sw)) OR SETCHANGED(startTime(sw)))
    AND NOT CHANGED(endTime(sw)) AND startDate(sw) AND startTime(sw) DO {
    LOCAL endDateTime = DATETIME (ServiceWork);
    endDateTime(sw) <- sumMinutes(dateTimeToDateTime(startDate(sw), startTime(sw)), duration(sw) * 60);
    endDate(sw) <- DATE(endDateTime(sw));
    endTime(sw) <- TIME(endDateTime(sw));
}

note 'Note' = DATA ISTRING (ServiceWork) CHARWIDTH 20;

distance 'Расстояние' = DATA NUMERIC[5,1] (ServiceWork);

FORM serviceWork 'Активность'
    OBJECTS o = ServiceWork PANEL
    PROPERTIES(o) numberServiceOrder, nameItemServiceOrder READONLY, nameAssignee, 
        nameAssignees  ON CHANGE {SHOW serviceWorkAssignees OBJECTS sw = o;}, nameServiceOperation,
        startDate, startTime, duration, endDate, endTime, distance,
        note

    EDIT ServiceWork OBJECT o
;

DESIGN serviceWork {
    caption = badged('Активности', nameNumberServiceOrder(o));
    OBJECTS {
        NEW header {
            alignment = STRETCH;
            horizontal = TRUE;
            NEW headerLeft {
                MOVE PROPERTY(numberServiceOrder(o));
                MOVE PROPERTY(nameServiceOperation(o));
                MOVE PROPERTY(nameAssignee(o)) { notNull = TRUE; }
                MOVE PROPERTY(nameAssignees(o));
            }
            NEW headerRight {
                MOVE PROPERTY(nameItemServiceOrder(o));
                MOVE PROPERTY(startDate(o));
                MOVE PROPERTY(startTime(o));
                MOVE PROPERTY(duration(o)) { caption = 'Длительность, часов'; };
                MOVE PROPERTY(endDate(o));
                MOVE PROPERTY(endTime(o));
                MOVE PROPERTY(distance(o));
            }
        }
        MOVE PROPERTY(note(o));
        NEW details {
            fill = 1;
            tabbed = TRUE;
        }
    }
}

@defineHistoryObject(serviceWork);
@defineHistoryProperty(serviceWork, status, 'Status', nameStatus);
@defineHistoryProperty(serviceWork, assignee, 'Assignee', nameAssignee);

@defineHistoryProperty(serviceWork, serviceOperation, 'Service operation', nameServiceOperation);

background = ABSTRACT CASE COLOR (ServiceWork);

FORM serviceWorks 'Активности'
    OBJECTS o = ServiceWork BACKGROUND background(o)
    PROPERTIES(o) READONLYIF isReadonly()
    name, numberServiceOrder, nameItemServiceOrder, nameAssignee, nameAssignees, nameServiceOperation,
        startDate, startTime, duration, endDate, endTime, distance
    //PROPERTIES(o) NEWSESSION NEW, EDIT, DELETE

    FILTERGROUP active
        FILTER 'Opened' opened(o) DEFAULT
        FILTER 'Closed' closed(o)

    LIST ServiceWork OBJECT o
;

@extendFormEditable(serviceWorks);

@defineDocObjectsForm(serviceWorks, o, 'Активности');
@defineDocStatusForm(serviceWork, o, name, ready, 'Ready');

@defineHistoryForm(serviceWork, serviceWork, o);

@defineObjectComments(serviceWork, o, details);

NAVIGATOR {
    operations {
        NEW serviceWorks;
    }
}

EXTEND FORM order
    OBJECTS sw = ServiceWork
    PROPERTIES(sw) imagedNameStatus BACKGROUND colorStatus(sw), nameServiceOperation, nameAssignees ON CHANGE {SHOW serviceWorkAssignees OBJECTS sw = sw;}
    , note, 
            startDate, startTime, duration, endDate, endTime, distance
    PROPERTIES(sw) NEW, DELETE
    FILTERS serviceOrder(sw) = o
;

DESIGN order {
    works {
        MOVE BOX(sw) {
            fill = 1;
            caption = badged('Активности', countServiceWork(o));
            PROPERTY(duration(sw)) { caption = 'Продолжительность, часов';}
        }
    }
}

clone (Order to, Order from) + {
    responsible(to) <- responsible(from);
    scheduledDateTime(to) <- scheduledDateTime(from);
    FOR serviceOrder(ServiceWork sw) = from NEW ol = ServiceWork DO {
        serviceOrder(ol) <- to;
        serviceOperation(ol) <- serviceOperation(sw);
        assignee(ol) <- assignee(sw);
        startDate(ol) <- startDate(sw);
        startTime(ol) <- startTime(sw);
        duration(ol) <- duration(sw);
        endDate(ol) <- endDate(sw);
        endTime(ol) <- endTime(sw);
        distance(ol) <- distance(sw);
        note(ol) <- note(sw);
    }
}

scheduleItem = DATA LOCAL Item ();
nameScheduleItem 'Продукт' () = name(scheduleItem());

duration 'Duration' (DATE d, Item c) =
    GROUP SUM duration(ServiceWork w) IF startDate(w) = d AND item(serviceOrder(w)) = c AND (c = scheduleItem() OR NOT scheduleItem());

backgroundDuration (DATE d) = CASE WHEN d = currentDate() THEN RGB(224,255,224)
    WHEN extractDOWNumber(d) = 0 OR extractDOWNumber(d) = 6 THEN RGB(255,224,224);

backgroundDuration (DATE d, Item i) =
    IF duration(d, i) THEN RGB(224,224,255)
    ELSE backgroundDuration(d);

FORM workOrderDateItem 'Активности'
    OBJECTS d = DATE PANEL
    OBJECTS i = Item PANEL

    OBJECTS w = ServiceWork
    PROPERTIES(w) READONLY numberServiceOrder, nameAssignees, note, nameServiceOperation, 
            startTime, duration,  endDate, endTime, distance
    PROPERTIES(w) NEWSESSION NEW, EDIT, DELETE
    FILTERS startDate(w) = d,
        item(serviceOrder(w)) = i
;

EXTEND FORM orders
    OBJECTS dates = INTERVAL[DATE] PANEL NULL
    PROPERTIES dates '' = VALUE(dates)

    PROPERTIES() scheduleItem

    OBJECTS d = DATE
    FILTERS iterate(d, from(dates), to(dates))

    OBJECTS i = Item
    PROPERTIES(i) READONLY name
    PROPERTIES duration 'Duration' = HTML(durationToChar(duration(d, i)))
    COLUMNS (d) HEADER extractDay(d) BACKGROUND backgroundDuration(d, i)
    ON CHANGE {
        SHOW workOrderDateItem OBJECTS d = d, i = i FLOAT;
    }
    FILTERS GROUP SUM duration(ServiceWork w) IF item(serviceOrder(w)) = i

    EVENTS ON INIT {
        SEEK orders.dates = interval(firstDayOfMonth(currentDate()), lastDayOfMonth(currentDate()));
    }

    PROPERTIES prevInterval '<' = { SEEK orders.dates = prevMonthInterval(dates); },
        nextInterval '>' = { SEEK orders.dates = nextMonthInterval(dates); }
;

DESIGN orders {
    tabbedPane {
        NEW schedule {
            caption = 'График';
            NEW header {
                alignment = STRETCH;
                horizontal = TRUE;
                NEW interval {
                    horizontal = TRUE;
                    MOVE PROPERTY(prevInterval);
                    MOVE PROPERTY(dates);
                    MOVE PROPERTY(nextInterval);
                }
                MOVE PROPERTY(scheduleItem());
            }
            MOVE BOX(i) {
                caption = '';
                PROPERTY(duration) {
                    charWidth = 4;
                }
            }
        }
    }
}

edit (ServiceWork l) + { edit(serviceOrder(l)); } 