MODULE ServiceOrderType;

REQUIRE ServicesSettings, Location;

NAMESPACE Services;

CLASS OrderType 'Services order type';

name '{Name}' = DATA STRING[50] (OrderType) NONULL IN id;

id '{ID}'= DATA STRING[20] (OrderType);
serviceOrderType = GROUP AGGR OrderType t BY id(t);

numerator 'Numerator' = DATA Numerator (OrderType);
nameNumerator 'Numerator' (OrderType o) = name(numerator(o));

materialsLocation 'Materials location' = DATA Location (OrderType);
nameMaterialsLocation 'Materials location' (OrderType t) = name(materialsLocation(t));

FORM orderType 'Services order type'
    OBJECTS o = OrderType PANEL
    PROPERTIES(o) name, id, nameNumerator, nameMaterialsLocation

    EDIT OrderType OBJECT o;
;

DESIGN orderType {
    OBJECTS {
        NEW header {
            horizontal = TRUE;
            MOVE PROPERTY(name(o)) { charWidth = 30; }
            MOVE PROPERTY(id(o));
            MOVE PROPERTY(nameNumerator(o));
        }
        NEW pane {
            lines = 3;
            NEW default {
                caption = 'Default';
                MOVE PROPERTY(nameMaterialsLocation(o));
            }
            NEW otherInformation {
                caption = 'Other information';
            }
        }
        NEW tabbedPane {
            fill = 1;
            tabbed = TRUE;
        }
    }
}

FORM orderTypes 'Types of production orders'
    OBJECTS o = OrderType
    PROPERTIES(o) READONLY name, id

    LIST OrderType OBJECT o;
;

EXTEND FORM options
    OBJECTS ot = OrderType
    PROPERTIES(ot) READONLY name, id
    PROPERTIES(ot) NEWSESSION NEW, EDIT, DELETE
;

DESIGN options {
    tabbedPane {
        MOVE BOX(ot);
    }
}

countOrderTypes 'Number of types' () = GROUP SUM 1 IF r IS OrderType;
firstOrderType () = GROUP LAST OrderType t ORDER DESC t WHERE t IS OrderType;

defaultOrderType () = firstOrderType()
    IF countOrderTypes() = 1;
