MODULE ServiceOperation;

REQUIRE ServicesSettings;

NAMESPACE Services;

CLASS Operation 'Services operation';

name '{Name}' = DATA STRING[50] (Operation) NONULL IN id;

id '{ID}'= DATA STRING[20] (Operation);
serviceOperation = GROUP AGGR Operation t BY id(t);

FORM operation 'Services operation'
    OBJECTS o = Operation PANEL
    PROPERTIES(o) name, id

    EDIT Operation OBJECT o;
;

DESIGN operation {
    OBJECTS {
        NEW header {
            horizontal = TRUE;
            MOVE PROPERTY(name(o)) { charWidth = 30; }
            MOVE PROPERTY(id(o));
        }
        NEW pane {
            lines = 3;
            NEW otherInformation {
                caption = 'Other information';
            }
        }
        NEW tabbedPane {
            fill = 1;
            tabbed = TRUE;
        }
    }
}

FORM operations 'Types of production orders'
    OBJECTS o = Operation
    PROPERTIES(o) READONLY name, id

    LIST Operation OBJECT o;
;

EXTEND FORM options
    OBJECTS oo = Operation
    PROPERTIES(oo) READONLY name, id
    PROPERTIES(oo) NEWSESSION NEW, EDIT, DELETE
;

DESIGN options {
    tabbedPane {
        MOVE BOX(oo);
    }
}

countOperations 'Number of types' () = GROUP SUM 1 IF r IS Operation;
firstOperation () = GROUP LAST Operation t ORDER DESC t WHERE t IS Operation;

defaultServiceOperation () = firstOperation()
    IF countOperations() = 1;

